name: App Container Build and Upload


on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        
        steps:

        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Building Container
          run: docker build -t etheral-excerpts .

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Push Docker Image
          run: |
            docker tag etheral-excerpts ${{ secrets.DOCKERHUB_USERNAME }}/etheral-excerpts
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/etheral-excerpts


